[tool.black]
line-length = 99
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
  (
    /(
      | \.git          # root of the project
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
  )
  '''
