AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

max_workers: ${MAX_WORKERS:100}

TWITTER:
  CONSUMER_KEY: ${CONSUMER_KEY}
  CONSUMER_SECRET: ${CONSUMER_SECRET}
  ACCESS_TOKEN: ${ACCESS_TOKEN}
  ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}

TIMELINE_INTERVAL: ${TIMELINE_INTERVAL}
TIMELINE_DAYS_BACK: ${TIMELINE_DAYS_BACK}
